version: '3.1'

services:

  mongodb:
    image: mongo
    expose:
      - 27017
    logging:
      driver: "none"

  rsscloud:
    build: .
    image: rsscloud
    command: node --use_strict app.js
    environment:
      DOMAIN: rsscloud
      PORT: 5337
      MONGODB_URI: mongodb://mongodb:27017/rsscloud
      NODE_TLS_REJECT_UNAUTHORIZED: 0
    expose:
      - 5337
    depends_on:
      - mongodb
    logging:
      driver: "none"

  rsscloud-tests:
    image: rsscloud
    command: dockerize -wait tcp://mongodb:27017 -wait http://rsscloud:5337 -timeout 10s bash -c "npm test"
    environment:
      APP_URL: http://rsscloud:5337
      MONGODB_URI: mongodb://mongodb:27017/rsscloud
      MOCK_SERVER_URL: http://rsscloud-tests:8002
      MOCK_SERVER_PORT: 8002
      SECURE_MOCK_SERVER_URL: https://rsscloud-tests:8003
      SECURE_MOCK_SERVER_PORT: 8003
    expose:
      - 8002
      - 8003
    depends_on:
      - mongodb
      - rsscloud
